sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: linux
      dist: yakkety
      sudo: false

addons:
  apt:
    packages:
    - libwebp-dev
    - webp

branches:
  only:
    - master

php:
  - 7

install: travis_retry composer install --no-interaction

script: lib/vendor/bin/phpunit --configuration phpunit.xml.dist